version: "3.8"
services:
  app:
    image: tripwith:latest
    container_name: app-blue
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ap-northeast-2
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      JWT_ACCESS_TOKEN_EXPIRATION: 3600
      JWT_REFRESH_TOKEN_EXPIRATION: 604800
      JWT_SECRET: ${JWT_SECRET}
